---
title: "DATA 607 2B"
author: "Desiree Thomas"
format: html
editor: visual
---

## Approach

When I was a teen I used to volunteer at the NY Aquarium as a Docent. One of my animal specialities were the African Penguins (along with Sharks and Sea Lions). Fun times!

## Potential Business/Non-Profit Problem

Please note that I don't actually know how conservationists make their decisions. This is a background story for this assignment. Do not take it as fact. These are a "I watched National Geographic documentary" type background stories. 

National Geogrpahic Style. A conservation team received a grant to study the migration patterns of female African Penguins. They received a certain number of satellite trackers to attach to female penguins so the team can track their egg-laying migrations. Falsely predicting a penguin is female would cost them an entire satellite tracker and is wasted grant money. These penguins are sexually monomorphic. I suppose you could also use this for a breding program?

https://www.cbsnews.com/pittsburgh/news/2-african-penguin-chicks-national-aviary/

Outline: 

I need to do a survey of the population by exploring the data through a class balance by counting the sexes (males vs. females). I should calcultate the null error rate. This is important because what if we guessed female for every bird? How often would we/the team be wrong? This is important for the model to not guess the majoritybut to also identify the minority class. I will use the counts for max and sum then calculate the null error rate, majority/total. 



I need to create the three confusion matrices. This breaks down the performance of a classification model by telling you how it was wrong. I have to set the threshold and compare the columns and sort them into Correct and Wrong predictions. Ex. Guess: Female, Actual: Female, Prediction: Correct vs. Guess: Female, Actual: Male, Prediction: Wrong. 

I have to continue studying so I can understand what I need to actually code out. I have a plan, which will evolve in the codebase. 

